"""Backtest metrics (FINAL_DELIVERABLE §Y).

Reported for every run: trades · win/loss · gross_R · net_R · avg_R · expectancy ·
profit_factor · max_dd_R · max consecutive losses · tail loss (5th pct) · Sharpe ·
Sortino · fill rate · recovery factor · per-regime breakdown.
"""

from __future__ import annotations

import math
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field


@dataclass
class TradeResult:
    signal_id: str
    symbol: str
    strategy: str
    regime: str
    direction: str
    filled: bool
    outcome: str  # TP1..TP4 | SL | EXPIRED | MISSED | INVALIDATED
    gross_r: float = 0.0
    gross_profit_r: float = 0.0
    gross_loss_r: float = 0.0
    net_r: float = 0.0
    mfe_r: float = 0.0
    mae_r: float = 0.0
    bars_held: int = 0
    entry: float = 0.0
    exit_price: float = 0.0
    tp_hits: tuple[int, ...] = ()


@dataclass
class Metrics:
    trades: int = 0
    entry_attempts: int = 0
    fills: int = 0
    wins: int = 0
    losses: int = 0
    gross_r: float = 0.0
    gross_profit_r: float = 0.0
    gross_loss_r: float = 0.0
    net_r: float = 0.0
    avg_r: float = 0.0
    expectancy: float = 0.0
    profit_factor: float = 0.0
    max_dd_r: float = 0.0
    max_consecutive_losses: int = 0
    tail_loss_5pct: float = 0.0
    sharpe: float = 0.0
    sortino: float = 0.0
    fill_rate: float = 0.0
    recovery_factor: float = 0.0
    tp_reach: Mapping[str, int] = field(default_factory=dict)
    sl_rate: float = 0.0
    expiry_rate: float = 0.0
    expiries: int = 0
    misses: int = 0
    per_regime: Mapping[str, float] = field(default_factory=dict)
    per_strategy: Mapping[str, float] = field(default_factory=dict)
    per_pair: Mapping[str, float] = field(default_factory=dict)
    equity_curve: Sequence[float] = field(default_factory=tuple)
    veto_rate: float = 0.0
    signal_frequency_per_day: float = 0.0

    def as_dict(self) -> dict[str, object]:
        return {
            "trades": self.trades,
            "entry_attempts": self.entry_attempts,
            "fills": self.fills,
            "wins": self.wins,
            "losses": self.losses,
            "win_rate": round(self.wins / self.fills, 4) if self.fills else 0.0,
            "gross_r": round(self.gross_r, 4),
            "gross_profit_r": round(self.gross_profit_r, 4),
            "gross_loss_r": round(self.gross_loss_r, 4),
            "net_r": round(self.net_r, 4),
            "avg_r": round(self.avg_r, 4),
            "expectancy": round(self.expectancy, 4),
            "profit_factor": round(self.profit_factor, 4),
            "max_dd_r": round(self.max_dd_r, 4),
            "max_consecutive_losses": self.max_consecutive_losses,
            "tail_loss_5pct": round(self.tail_loss_5pct, 4),
            "sharpe": round(self.sharpe, 4),
            "sortino": round(self.sortino, 4),
            "fill_rate": round(self.fill_rate, 4),
            "recovery_factor": round(self.recovery_factor, 4),
            "sl_rate": round(self.sl_rate, 4),
            "expiry_rate": round(self.expiry_rate, 4),
            "expiries": self.expiries,
            "misses": self.misses,
            "veto_rate": round(self.veto_rate, 4),
            "tp_reach": dict(self.tp_reach),
            "per_regime": {k: round(v, 4) for k, v in self.per_regime.items()},
            "per_strategy": {k: round(v, 4) for k, v in self.per_strategy.items()},
            "per_pair": {k: round(v, 4) for k, v in self.per_pair.items()},
        }


def compute_metrics(
    trades: Sequence[TradeResult],
    *,
    signals_considered: int = 0,
    vetoed: int = 0,
    days: float = 0.0,
    fills: int | None = None,
    expiries: int = 0,
    misses: int = 0,
) -> Metrics:
    # Every returned TradeResult represents one entry attempt generated by the engine.
    # `trades` is strictly the number of filled/closed positions; fill rate is fills / attempts.
    attempts = list(trades)
    executed = [t for t in attempts if t.filled]
    m = Metrics(trades=len(executed), entry_attempts=len(attempts))
    m.fills = int(fills) if fills is not None else len(executed)
    m.expiries = int(expiries) if expiries else sum(1 for t in attempts if t.outcome == "EXPIRED")
    m.misses = int(misses) if misses else sum(1 for t in attempts if t.outcome in ("MISSED", "INVALIDATED"))
    m.wins = sum(1 for t in executed if t.net_r > 0)
    m.losses = sum(1 for t in executed if t.net_r <= 0)
    m.gross_r = sum(t.gross_r for t in executed)
    m.gross_profit_r = sum(t.net_r for t in executed if t.net_r > 0)
    m.gross_loss_r = sum(abs(t.net_r) for t in executed if t.net_r <= 0)
    m.net_r = sum(t.net_r for t in executed)
    m.avg_r = m.net_r / len(executed) if executed else 0.0
    m.expectancy = m.avg_r
    if m.gross_loss_r > 0:
        m.profit_factor = m.gross_profit_r / m.gross_loss_r
    elif m.gross_profit_r > 0:
        m.profit_factor = float("inf")
    else:
        m.profit_factor = 0.0

    equity = 0.0
    peak = 0.0
    curve: list[float] = []
    streak = 0
    max_streak = 0
    for trade in executed:
        equity += trade.net_r
        curve.append(equity)
        peak = max(peak, equity)
        m.max_dd_r = max(m.max_dd_r, peak - equity)
        if trade.net_r <= 0:
            streak += 1
            max_streak = max(max_streak, streak)
        else:
            streak = 0
    m.max_consecutive_losses = max_streak
    m.equity_curve = tuple(curve)

    returns = [t.net_r for t in executed]
    if len(returns) >= 2:
        mean_r = sum(returns) / len(returns)
        sd = math.sqrt(sum((r - mean_r) ** 2 for r in returns) / (len(returns) - 1))
        m.sharpe = (mean_r / sd) * math.sqrt(len(returns)) if sd > 0 else 0.0
        downside = [r for r in returns if r < 0]
        dsd = math.sqrt(sum(r**2 for r in downside) / len(downside)) if downside else 0.0
        m.sortino = (mean_r / dsd) * math.sqrt(len(returns)) if dsd > 0 else 0.0
    if returns:
        ordered = sorted(returns)
        idx = max(0, int(math.floor(0.05 * (len(ordered) - 1))))
        m.tail_loss_5pct = ordered[idx]

    m.tp_reach = {f"TP{i}": sum(1 for t in executed if i in t.tp_hits) for i in (1, 2, 3, 4)}
    m.tp_reach["SL"] = sum(1 for t in executed if str(t.outcome).startswith("SL"))
    m.sl_rate = m.tp_reach["SL"] / len(executed) if executed else 0.0
    m.fill_rate = (m.fills / m.entry_attempts) if m.entry_attempts else 0.0
    m.expiry_rate = (sum(1 for t in attempts if str(t.outcome).upper() == "EXPIRED") / m.entry_attempts) if m.entry_attempts else 0.0
    m.recovery_factor = (m.net_r / m.max_dd_r) if m.max_dd_r > 0 else 0.0
    m.veto_rate = (vetoed / signals_considered) if signals_considered else 0.0
    m.signal_frequency_per_day = (m.entry_attempts / days) if days > 0 else 0.0

    m.per_regime = _group(executed, key=lambda t: t.regime or "UNKNOWN")
    m.per_strategy = _group(executed, key=lambda t: t.strategy or "UNKNOWN")
    m.per_pair = _group(executed, key=lambda t: t.symbol)
    return m


def _group(trades: Sequence[TradeResult], *, key) -> dict[str, float]:
    buckets: dict[str, list[float]] = {}
    for trade in trades:
        buckets.setdefault(key(trade), []).append(trade.net_r)
    return {k: (sum(v) / len(v)) if v else 0.0 for k, v in buckets.items()}


def render_metrics(metrics: Metrics) -> str:
    lines = ["Backtest metrics", "-" * 60]
    for key, value in metrics.as_dict().items():
        if isinstance(value, dict):
            lines.append(f"{key}:")
            for sub_key, sub_value in sorted(value.items()):
                lines.append(f"    {sub_key}: {sub_value}")
        else:
            lines.append(f"{key}: {value}")
    return "\n".join(lines)


__all__ = ["Metrics", "TradeResult", "compute_metrics", "render_metrics"]
